### PR TITLE
Make compatible with standard library version 1.4

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by gallais** [comment]
You probably need to update the `.travis.yml` file to use v1.4 too:

https://github.com/agda/agda-categories/blob/ad0f94b6cf18d8a448b844b021aeda58e833d152/.travis.yml#L19

**Comment by turion** [comment]
I accidentally misnamed the branch.

**Comment by JacquesCarette** [comment]
Thanks, I'll investigate asap, but it might not be until the weekend (sorry). Someone else might beat me to it.

**Comment by Taneb** [comment]
I think `Relation.Binary.Construct.Closure.SymmetricTransitive` should be removed from `Everything.agda` as well

**Comment by turion** [comment]
@Taneb, well spotted, done.

**Comment by HuStmpHrrr** [comment]
@JacquesCarette do you have something in mind? to what I can see it seems good to go.

**Comment by JacquesCarette** [comment]
Nothing in particular, I just didn't have the time to look at the details at all. So if it looks good to you @HuStmpHrrr go ahead and merge it.

**Pull request merged**
