### PR TITLE
make it work with the agda stdlib v2.0 (c12568c64)

### PR DESCRIPTION
**Pull request by cmcmA20**
^subj

### CODE REVIEW

**Comment by MatthewDaggitt** [comment]
A heads up that `v2.0` is not released so I wouldn't recommend merging this in, unless you want your users to have to upgrade to the unstable library version.

**Comment by cmcmA20** [comment]
Let it chill until then, I will update it after release.

**Comment by cmcmA20** [comment]
Tested with agda master `269204b682`
Works on agda-stdlib master `7c5f3ff90`

**Comment by JacquesCarette** [comment]
Thanks.  [Note: there seems to be two outstanding conflicts?]

**Comment by JacquesCarette** [comment]
So now that `stdlib` 2.0 is 'essentially' live, it would be nice to revisit this. Looks like things have broken since this was last looked at.

**Comment by JacquesCarette** [comment]
If you give me permission to push to your branch, I can help.

**Comment by JacquesCarette** [comment]
In the end, 64 different places needed to be fixed to push things to 2.0, and this was done in #406 which has been merged. So this one is no longer needed - but keep PRs coming!

**Pull request closed without merging**
