### PR TITLE
Distributive Category

### PR DESCRIPTION
**Pull request by Reijix**
Distributive categories as described [here](https://ncatlab.org/nlab/show/distributive+category) and their relationship to extensive categories (an extensive and cartesian category is automatically distributive).

I needed some properties of coproducts (namely `up-to-iso` and `Mobile`) so I added them, but I was wondering if they have been left out on purpose and I should've used Duality?

Lastly I've also added bundled versions `ExtensiveCategory` and `ExtensiveDistributiveCategory`.

### CODE REVIEW

**Comment by sergey-goncharov** [comment]
I suggest refactoring this, by using `IsCoproduct` than working with two coproducts and involving explicit up-to-isomorphism reasoning. To facilitate this, I've added a lemma `pullback-of-cp-is-cp'` to `Categories.Category.Extensive` -- the relevant PR https://github.com/agda/agda-categories/pull/384 is pending.

**Comment by Reijix** [comment]
> I suggest refactoring this, by using IsCoproduct than working with two coproducts and involving explicit up-to-isomorphism reasoning. To facilitate this, I've added a lemma pullback-of-cp-is-cp' to Categories.Category.Extensive -- the relevant PR https://github.com/agda/agda-categories/pull/384 is pending.

Great, I'll adjust the proof once it is finished. This will shorten `distrib` and make `distrib-canon` obsolete.
Having both definitions is valuable I think, since `pullback-of-cp-is-cp` seems to be easier to proof, while `pullback-of-cp-is-cp'` is easier to work with.

**Comment by JacquesCarette** [comment]
I've asked for some changes to #384 , but the interface will stay the same. So you could `postulate` it while waiting.

**Comment by sergey-goncharov** [comment]
> Having both definitions is valuable I think, since `pullback-of-cp-is-cp` seems to be easier to proof, while `pullback-of-cp-is-cp'` is easier to work with.

A small didactic point: only `pullback-of-cp-is-cp` is (part of the) definition, `pullback-of-cp-is-cp'` is a (theorem or) lemma, so a derivable statement. **Definitions** must possibly be designed so as to be as restrictive as possible (because we will have to check them for every instance), while derived claims must be as rich as possible (because, they are the generic facts that we obtain from the definitions "for free").

**Comment by JacquesCarette** [comment]
#384 has now been merged.

**Comment by Reijix** [comment]
Updated it now.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
