### PR TITLE
Implement the selection functor

### PR DESCRIPTION
**Pull request by TOTBWF**
This PR implements the lifting of functions on objects of discreet categories into functors. I'm open to a better name than `Select`, I just couldn't come up with any better ones myself.

### CODE REVIEW

**Comment by sstucki** [comment]
I think this is the action of the `Discrete` functor: https://github.com/agda/agda-categories/blob/master/src/Categories/Adjoint/Instance/Discrete.agda

So maybe one could call it `Discrete₁`?

I think it's a good idea to factor the components of adjoint functors into separate modules -- not least because they can often be made more universe-polymorphic that way. But we should probably try to come up with a system to consistently name and organize the corresponding modules.

**Comment by sstucki** [comment]
> I think this is the action of the Discrete functor

...whoops, I spoke too soon. This is a different (more general?) construction?

**Comment by JacquesCarette** [comment]
`FromDiscrete` ?  Especially if done via a qualified import, it could become `Functor.FromDiscrete`, which isn't too bad.  Variants on that idea might be even better, that's the one that came to mind now.

**Comment by JacquesCarette** [comment]
Do you have references for where this construction occurs?  That might help scrounge up a name too.

**Comment by TOTBWF** [comment]
I mostly need it for constructing (co)limits. For example, when viewing a (co)product as a (co)limit, you need a functor from the 2 element  discrete category to select your two objects.

`FromDiscrete` seems like it could be a good choice!

**Comment by JacquesCarette** [comment]
That application seems to have non-trivial overlap with what @HuStmpHrrr is doing with finite categories -- have you looked at that?

**Comment by sstucki** [comment]
> I mostly need it for constructing (co)limits. For example, when viewing a (co)product as a (co)limit, you need a functor from the 2 element discrete category to select your two objects.

But that seems very specific to (co)products, no? If you want to define (co)limits over diagrams with arrows (e.g. pullbacks/pushouts) a functor out of a discrete category won't work, right?

Still, I think it might be a useful abstraction for other purposes.

**Comment by HuStmpHrrr** [comment]
I don't think you can generate products from discrete categories. the category generating products as limits is the following

```
a <------- b -------> c
```

which is not discrete.

**Comment by TOTBWF** [comment]
@sstucki Yes, it doesn't work for limits over diagrams with non-identity arrows. However, I found myself implementing this functor for `Discrete Bool`, and realized that I could generalize it!

@HuStmpHrrr You do use a discrete category, see https://ncatlab.org/nlab/show/limits+and+colimits+by+example#product for more details.

There definitely seems to be some overlap with the finite category stuff. Maybe we could have a notion of a discrete shape for any finite type?

**Comment by HuStmpHrrr** [comment]
yes, you are right. I was not thinking.

**Comment by JacquesCarette** [comment]
How are we doing on finding a better name?

**Comment by TOTBWF** [comment]
I think `FromDiscreet` is the best one so far. Will make the changes later today

**Comment by HuStmpHrrr** [comment]
FYI, I am about to merge the finite category PR which I have prepared forever. from there, I proved a theorem which shows a limit can be derived from a finite shape if a category is finitely complete. special limits like products are easy corollaries.

**Comment by WolframKahl** [comment]
> I  think `FromDiscreet` is the best one so far. 

`FromDiscrete` ?

**Comment by TOTBWF** [comment]
>>    I think FromDiscreet is the best one so far.

> FromDiscrete ?

Looks like auto-correct has it's own opinions on what this should be named!

Anyways, I've renamed it to `FromDiscrete`, so this should be good to go.

**Pull request merged**
