### PR TITLE
added 2 simple but useful identities to HeterogeneousIdentity

### PR DESCRIPTION
**Pull request by MirceaS**

### CODE REVIEW

**Comment by JacquesCarette** [comment]
I'm assuming you're proposing these as you needed them in some development?

**Comment by MirceaS** [comment]
> I'm assuming you're proposing these as you needed them in some development?

I do indeed, and I thought it would be useful for them to go in here

**Comment by MirceaS** [comment]
Who else needs to Approve this before it can be merged?

**Comment by JacquesCarette** [comment]
I was giving others a bit of time to comment if they wanted.

**Pull request merged**
