### PR TITLE
Added a helper for Monoidal creation

### PR DESCRIPTION
**Pull request by MirceaS**
Because 3 of the fields can be proved from the other

### CODE REVIEW

**Comment by MirceaS** [comment]
> Isn't there a problem where this cannot be used, as `Monoidal'` is private, thus not externally visible? Or is it ok because `monoidalHelper` is always meant to be called on an explicit record?

I followed the 'helper' pattern present in `Categories.Category.Monoidal.Symmetric`. The simplified record is private there. I think this is because, ideally, you want to only call monoidalHelper on an explicit record as the new record is only used as an injection into the main record.

I was under the impression that `Categories.Category.Core` did the same thing, but there the primed record is not made private. So we might need to tweak that so that `Category` and Symmetric are consistent with eachother.

I'm happy to change my implementation to the style in `Core.agda` and make the primed record public if you feel like that would be better.

**Comment by JacquesCarette** [comment]
Right - I'm not sure we've evolved a style yet.  @HuStmpHrrr opinion?

**Comment by HuStmpHrrr** [comment]
`private` is OK because it actually prevents the definition from being (easily) referred to externally. the helper can still be used because ultimately it just wants a record, which can be defined anyways.

**Comment by JacquesCarette** [comment]
Ok, I'll merge as is then.

**Comment by MirceaS** [comment]
Should we also change the definition of `Category'` to be private as well then?

**Comment by JacquesCarette** [comment]
Probably, yes.  [I just don't want to do the 15 minute wait for `make` to ensure that it doesn't break anything right now, I've got a bunch of other things I should be working on.]

**Comment by MirceaS** [comment]
> Probably, yes. [I just don't want to do the 15 minute wait for `make` to ensure that it doesn't break anything right now, I've got a bunch of other things I should be working on.]

Can't we have GitHub do that automatically, as it does for agda-stdlib?
There, any PR is checked using Travis-CI

**Comment by JacquesCarette** [comment]
Yes - we even have an open issue for that. No one has yet tackled it.  If you'd like to, we'd be quite happy to merge that in!

**Comment by MirceaS** [comment]
> Yes - we even have an open issue for that. No one has yet tackled it. If you'd like to, we'd be quite happy to merge that in!

I look at the open issues and I didn't see anything about that...
I also noted that you have a `.travis.yml` file in the repo already? Were there any previous attempts to get Travis working in the past that didn't go through?

**Comment by JacquesCarette** [comment]
There are various discussion in issues #20 #91 #126 #131 and #140 .  Looks like Travis is currently only used for producing documentation, but not for automatic testing.  The problem, until 2.6.1, was that the library took too much memory to check.  Now it's ok.  So I think it's worth trying again.

**Comment by HuStmpHrrr** [comment]
when it generates the doc, it will need to compile the files first. that already suffices. usually a cycle takes around 40 minutes.

**Pull request merged**
