### PR TITLE
Rename slice functors

### PR DESCRIPTION
**Pull request by Taneb**
Extracted from https://github.com/agda/agda-categories/pull/408

### CODE REVIEW

**Comment by JacquesCarette** [comment]
FYI, swamped until Nov. 1. Will look after that.

**Comment by Taneb** [comment]
@JacquesCarette are you able to give this a review now?

**Comment by JacquesCarette** [comment]
Very soon. Catching up on all the things I didn't do last week. This is explicitly on that list.

**Review by JacquesCarette — APPROVED** [review]
This is great, thanks. Sorry for the super-long wait, I've been ridiculously swamped. Even fun things (like this) had to wait!

**Pull request merged**
