### PR TITLE
Update to standard-library 1.7.1

### PR DESCRIPTION
**Pull request by iblech**

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Apparently it's not that simple?

**Comment by iblech** [comment]
It is :-) You can test it using:

> nix-shell -I nixpkgs=https://github.com/iblech/nixpkgs/archive/patch-agda-stdlib1.7.1.tar.gz -p "agda.withPackages (p: [ p.standard-library p.agda-categories ])"

(This pull request is a dependence of a pull request for NixOS, https://github.com/NixOS/nixpkgs/pull/147061.)

**Comment by JacquesCarette** [comment]
I saw that 1.7.1 was released just earlier today - I was just under the impression that the CI would grab the latest. If it doesn't, then something else needs adjusted too, so that CI passes.

**Comment by turion** [comment]
I think you need to bump the `STDLIB_VERSION` variable in github actions as well: https://github.com/agda/agda-categories/blob/1c027debdb615b4f941f08b81647c9be504a75b2/.github/workflows/ci-ubuntu.yml#L49

Otherwise CI will always pull the specific version 1.7

**Comment by MatthewDaggitt** [comment]
Just a heads up that upgrading to this release is purely optional. Doesn't change any actual Agda code, only makes the cabal file  compatible with GHC 9.2 (hence why it hasn't been announced).

**Comment by JacquesCarette** [comment]
I wasn't going to upgrade, but I also won't refuse a ready-made PR that makes it all work!

**Comment by iblech** [comment]
@MatthewDaggitt Thank you for the pointer! I force-pushed to my branch. Let's see what the CI will make of this! :-)

**Comment by JacquesCarette** [comment]
The CI liked it. I'm still vaguely reluctant.  Opinions?

**Comment by turion** [comment]
My two cents: If you merge it you'd have to bump (and eventually release) the `agda-categories` version as well, since it will not be compatible with `standard-library-1.7` anymore.

**Comment by MatthewDaggitt** [comment]
Ah, the perils of making our first backwards compatible release. We realise we don't have any mechanism for compatible versioning management :laughing:

**Comment by iblech** [comment]
Hm... yes indeed. Any thoughts on that? We could also patch agda-categories locally in nixpkgs.

**Comment by turion** [comment]
I think you should merge and bump `agda-categories`. Releases are simple to download, so people can stay with 1.7 if that's important to them.

**Comment by JacquesCarette** [comment]
I'm going to pull in a few more PRs first, and then merge-and-bump.

**Comment by pthariensflame** [comment]
Is this in process still?

**Comment by JacquesCarette** [comment]
The PRs that I wanted to pull in are in. I just have not had any time to devote to this in the last few weeks. Looks like the next 2 weeks are also a disaster, but clear up after that. I'd be happy to get a co-maintainer though from the people who have submitted many PRs previously, such as @TOTBWF or @sstucki .

**Comment by TOTBWF** [comment]
I'd be more than happy to help out!

**Comment by JacquesCarette** [comment]
> I'd be more than happy to help out!

Great - see your email for more.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
