### PR TITLE
Implement the Kleisli Comparison Functor

### PR DESCRIPTION
**Pull request by TOTBWF**
This PR implements the Kleisli Comparison functor, finishing up #78.

I tried to prove uniqueness here as well, but ran into similar issues as before. It appears that the Coq development mentioned in the issue uses proof irrelevance/funext heavily, which would explain how they are able to prove it.

### CODE REVIEW

**Comment by TOTBWF** [comment]
Not sure why the CI is failing here, looks like it couldn't checkout agda properly?

**Comment by JacquesCarette** [comment]
I'm going to guess that CI is failing because others were experimenting with various settings (lots of comments on a couple of related issues), and you submitted at a time when things were broken. I see nothing in your code that would cause a problem.

Rather than prove 'strict' uniqueness, you might want to show it up to natural isomorphism using a trivial NI (i.e. both natural transformations being the identity).

**Comment by TOTBWF** [comment]
I tried the natural transformation route originally, but you still get mired down, as you have to use heterogeneous identity morphisms to establish the natural transformations.

**Comment by TOTBWF** [comment]
After some work, I was able to get a proof of uniqueness up to NI, but it does require UIP. Perhaps it is time to start work on #58.

**Comment by JacquesCarette** [comment]
Do you have the work checked-in to some branch?  I'd like to take a look.

That something **requires** UIP would be quite interesting, especially if it could in fact be shown to be equivalent to it.

**Pull request merged**
